language: node_js
node_js:
- v4
services: mongodb
deploy:
  provider: npm
  email: malykhinvi@gmail.com
  api_key:
    secure: VjfPWkvU/xL1mwdXg52WUC222nv7vtB9Hi4UNqQaaySSrdVOFXjXeqFQVVE44x9lNeQfjFtvOpfYlceEL/2r24xltDBlCy5ATK0Y2j5y9BhWAhHa96sXnaf/JnM1D14SSUWGjA4k5Gnz2FabgjpXEDoqZE/qTAy5k6GtdAwUduMf1ZK/rwZBZVJaa/acaLJFo737v8q9V8LWrr8X16SNXQsfwdqu9GbKG/v2HTpvtixKqToV6yiuTvxrp5G4ctWIkKm4ZJ5MgCVqLLoTHxLdIv4SsQNwOM4fbFbf6DNowqLfgpF6HeDUQJSKqwk6IOMWSeQ0y9S8hXvF7qwWbgXx/A+IowY3b9sy/tfjGXj08bfwFvAuKOhozFDdZ5Mkx1lJfINj6TuES/B1mgELWQrwIPpYNnkK6LecBULZX6kZOKd4F7ww5EBhqu8bWwzyScQyDHfzl4wo09pdu0tVcHUaB1CZaNXHF0STkqRx3BHnTFJSIVGogd6aOnsD5zZb9SttrEbYazm30/4t/OHwO9xGuZ2cZEPN7xEgu2ycmz6zxV0DEkVzStOsEfSEp6YjpCSn5MMQcS2jk/cjR7zaKX72sfg7Zur+PogjQjZzpPQYtX8szVVWIazRUBNw0iL808HKaDGLg4nPyPEfLpRIwwBhbH3QeRyEslkKtQq22lNwSnU=
  on:
    repo: mongodb-changelog